// Auto-generated from docs
export const GUIDES = [
    {
        "title": "1. Trợ lý Sinh Nội Dung AI (AI Writer)",
        "html": "<h1>1. Trợ lý Sinh Nội Dung AI (AI Writer)</h1>\n<p><strong>Mục đích:</strong> Tính năng cốt lõi giúp tự động viết các bài báo, bài blog chuẩn SEO một cách nhanh chóng.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Từ khoá (Keyword):</strong> Nhập từ khóa chính để AI tập trung viết bài chuẩn xác.</li>\n<li><strong>Cấu trúc Heading (H1, H2, H3):</strong> <ul>\n<li>Khung dàn ý tự động: Hiển thị các tiêu đề được sinh ra. Bạn có thể sửa, thêm bớt H2, H3 theo ý muốn.</li>\n</ul>\n</li>\n<li><strong>Độ dài bài viết:</strong> Giới hạn số lượng từ của bài viết (ví dụ: Tối đa 1000 từ).</li>\n<li><strong>Phân tích SEO:</strong><ul>\n<li><code>Độ dài Meta Description</code>: Cảnh báo nếu meta description dài quá 160 ký tự.</li>\n<li><code>Mật độ từ khóa</code>: Số lượng lặp lại của Main keyword trong bài viết.</li>\n</ul>\n</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Dựng kịch bản (Outline):</strong> Ra lệnh cho AI tự động sinh ra các tiêu đề (Heading) trước khi viết.</li>\n<li><strong>Tạo thành bài (Generate):</strong> Tiến hành viết nội dung chi tiết dựa trên Outline vừa tạo.</li>\n<li><strong>Bôi đen &amp; Chỉnh sửa nhanh:</strong><ul>\n<li><code>Viết lại</code>: Viết lại đoạn văn vừa bôi đen với lối hành văn khác.</li>\n<li><code>Làm dài ra</code>: Phân tích sâu và thêm chữ cho đoạn văn.</li>\n<li><code>Hỏi về nội dung</code>: Yêu cầu AI giải thích đoạn vừa bôi đen.</li>\n</ul>\n</li>\n</ul>\n"
    },
    {
        "title": "2. Quét Website và Sitemap (AI Crawl)",
        "html": "<h1>2. Quét Website và Sitemap (AI Crawl)</h1>\n<p><strong>Mục đích:</strong> Hỗ trợ thu thập ý tưởng, bài viết và cấu trúc của website đối thủ để lấy nguyên liệu cho việc sinh bài viết tự động.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Nhập URL hoặc Link Sitemap:</strong> Dán đường dẫn gốc của website hoặc file <code>.xml</code> chứa sitemap.</li>\n<li><strong>Lọc theo danh mục:</strong> Cho phép chỉ quét bài viết thuộc một URL cụ thể.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Crawl dữ liệu:</strong> Bắt đầu quá trình quét tự động. Hệ thống sẽ liệt kê hàng loạt các bài viết tìm thấy.</li>\n<li><strong>Chọn tất cả (Select All):</strong> Chọn toàn bộ danh sách bài viết.</li>\n<li><strong>Export/Import Links:</strong> Xuất danh sách URL đã quét ra file, hoặc nhập danh sách URL từ bên ngoài vào.</li>\n<li><strong>Đưa sang AI Writer:</strong> Đẩy các bài viết đã chọn sang công cụ AI Writer để Spin/Viết lại.</li>\n</ul>\n"
    },
    {
        "title": "3. Chuyển văn bản thành giọng nói (Text to Speech)",
        "html": "<h1>3. Chuyển văn bản thành giọng nói (Text to Speech)</h1>\n<p><strong>Mục đích:</strong> Chuyển đổi văn bản, bài viết thành file âm thanh chất lượng cao, tự nhiên như giọng người thật.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Văn bản cần đọc:</strong> Khung textbox để nhập nội dung bạn muốn AI đọc.</li>\n<li><strong>Chọn Giọng đọc (Voice):</strong> Dropdown hỗ trợ nhiều giọng đọc (Nam/Nữ, vùng miền, truyền cảm, đọc tin tức).</li>\n<li><strong>Tốc độ đọc (Rate):</strong> Cho phép chỉnh tốc độ từ 0.5x (rất chậm) đến 2.0x (rất nhanh). Mặc định là 1.0x.</li>\n<li><strong>Cao độ (Pitch):</strong> Tùy chỉnh độ trầm bổng của giọng đọc (Deep, Clear, High).</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Chuyển đổi thành Audio:</strong> Bắt đầu tiến trình tạo file mp3.</li>\n<li><strong>Nghe thử (Play / Waveform):</strong> Trình phát âm thanh trực quan dạng sóng (Waveform) cho phép bạn nghe thử trước khi lưu.</li>\n<li><strong>Tải xuống (Download):</strong> Lưu file <code>.mp3</code> hoặc <code>.wav</code> về máy tính.</li>\n</ul>\n"
    },
    {
        "title": "4. Quản lý Chatbot AI",
        "html": "<h1>4. Quản lý Chatbot AI</h1>\n<p><strong>Mục đích:</strong> Đào tạo và quản lý Chatbot AI tự động hỗ trợ khách hàng đa kênh (Fanpage, Website).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Nguồn dữ liệu đào tạo (Knowledge Base):</strong><ul>\n<li>Tải lên file tài liệu (PDF, Word, TXT) để Chatbot học kiến thức.</li>\n<li>Cung cấp đường dẫn website để Chatbot tự đọc toàn bộ nội dung.</li>\n</ul>\n</li>\n<li><strong>Cấu hình Prompt Chatbot:</strong> Điều chỉnh tính cách, xưng hô của Chatbot (ví dụ: Luôn xưng &quot;Dạ, em&quot;, đóng vai nhân viên tư vấn).</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Upload File:</strong> Bắt đầu tải tài liệu lên hệ thống để phân tích.</li>\n<li><strong>Kiểm tra kiến thức:</strong> Cửa sổ Test Bot, cho phép bạn chat thử với Bot để xem nó đã học thuộc bài chưa.</li>\n<li><strong>Bật / Tắt Bot:</strong> Tạm dừng tính năng trả lời tự động của Chatbot trên fanpage/website.</li>\n</ul>\n"
    },
    {
        "title": "5. Quản lý Profile (Gologin)",
        "html": "<h1>5. Quản lý Profile (Gologin)</h1>\n<p><strong>Mục đích:</strong> Nuôi và quản lý hàng loạt tài khoản mạng xã hội (Facebook, Tiktok) an toàn, tránh bị khóa (Check-point).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Tên Profile:</strong> Đặt tên gợi nhớ cho tài khoản.</li>\n<li><strong>Proxy:</strong> Gán IP Proxy (Socks5/HTTP) riêng biệt cho từng Profile.</li>\n<li><strong>User-Agent &amp; Fingerprint:</strong> Thiết lập thông số vân tay trình duyệt giả lập.</li>\n<li><strong>Cookies:</strong> Dán đoạn cookies để đăng nhập tài khoản mà không cần dùng mật khẩu.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Mở trình duyệt (Open):</strong> Chạy trình duyệt Gologin riêng lẻ với thông số đã được cô lập.</li>\n<li><strong>Đóng (Close):</strong> Tắt trình duyệt đang mở.</li>\n<li><strong>Chạy Script Kịch bản:</strong> Đẩy Profile vào vòng lặp Auto-farm (tự động thả tim, like, bình luận).</li>\n</ul>\n"
    },
    {
        "title": "6. Kiểm tra liên kết (SEO Check & Links)",
        "html": "<h1>6. Kiểm tra liên kết (SEO Check &amp; Links)</h1>\n<p><strong>Mục đích:</strong> Phân tích tình trạng liên kết (Links) bên trong website để tối ưu sức mạnh SEO On-page.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Đường dẫn Website:</strong> URL của trang bạn muốn phân tích.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Quét liên kết (Scan Links):</strong> Tìm toàn bộ Internal và External Links trên trang.</li>\n<li>Các biểu tượng phân tích:<ul>\n<li><strong>Lỗi 404:</strong> Chỉ ra các link bị hỏng (Broken links).</li>\n<li><strong>Thiếu Anchor Text:</strong> Báo cáo các thẻ <code>&lt;a&gt;</code> không có chữ hiển thị rõ ràng.</li>\n</ul>\n</li>\n<li><strong>Xuất Báo cáo:</strong> Tải file thống kê các đường dẫn lỗi để xử lý.</li>\n</ul>\n"
    },
    {
        "title": "7. Báo cáo SEO (GSC Report)",
        "html": "<h1>7. Báo cáo SEO (GSC Report)</h1>\n<p><strong>Mục đích:</strong> Theo dõi hiệu quả của website và thứ hạng từ khóa trực tiếp từ Google Search Console và Google Analytics.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>GA4 Property ID:</strong> Mã số thuộc tính Analytics.</li>\n<li><strong>Domain:</strong> Tên miền đang được kết nối với hệ thống.</li>\n<li><strong>Khoảng thời gian (Date Range):</strong> Lọc báo cáo (Ví dụ: 7 ngày qua, 30 ngày qua).</li>\n</ul>\n<h2>Ý nghĩa các thông số (Metrics)</h2>\n<ul>\n<li><strong>Total Users:</strong> Tổng số người dùng truy cập.</li>\n<li><strong>Screen Page Views:</strong> Lượt xem trang.</li>\n<li><strong>Engagement Rate:</strong> Tỷ lệ tương tác (%), tỷ lệ này càng cao chứng tỏ nội dung càng tốt.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Đồng bộ dữ liệu (Sync):</strong> Cập nhật dữ liệu real-time từ API của Google.</li>\n</ul>\n"
    },
    {
        "title": "8. Kịch bản Tài Khoản (Script Account)",
        "html": "<h1>8. Kịch bản Tài Khoản (Script Account)</h1>\n<p><strong>Mục đích:</strong> Thiết lập cấu hình hành động của các tài khoản ảo để &quot;nuôi nick&quot; hoặc spam an toàn.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Cấu hình độ trễ (Delay):</strong> Thời gian chờ giữa các hành động (VD: Đợi 5 - 10 giây trước khi like).</li>\n<li><strong>Trạng thái:</strong> Tắt/Bật tính năng bảo vệ chống ban tài khoản (Anti-Ban).</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Lưu Kịch bản:</strong> Ghi nhớ cấu hình Delay và Anti-Ban.</li>\n<li><strong>Gán cho Profile:</strong> Áp dụng kịch bản này cho danh sách Gologin Profiles bạn đã chọn.</li>\n</ul>\n"
    },
    {
        "title": "9. Kịch bản Tương tác TikTok",
        "html": "<h1>9. Kịch bản Tương tác TikTok</h1>\n<p><strong>Mục đích:</strong> Tạo kịch bản auto-farm riêng biệt cho mạng xã hội TikTok.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Link Video TikTok:</strong> Đường dẫn video bạn muốn cày view, tym hoặc comment.</li>\n<li><strong>Nội dung Bình luận:</strong> Danh sách các câu bình luận (Spintax hỗ trợ) để clone tự động gõ.</li>\n<li><strong>Hành động:</strong> <ul>\n<li>Lướt xem ngẫu nhiên (Random scroll).</li>\n<li>Thả tim (Like).</li>\n<li>Bấm theo dõi (Follow).</li>\n</ul>\n</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Chạy Tự Động (Run Script):</strong> Tiến hành điều khiển trình duyệt TikTok tự động.</li>\n<li><strong>Dừng (Stop):</strong> Dừng toàn bộ kịch bản.</li>\n</ul>\n"
    },
    {
        "title": "10. Kịch bản Tương tác Facebook",
        "html": "<h1>10. Kịch bản Tương tác Facebook</h1>\n<p><strong>Mục đích:</strong> Tạo kịch bản tương tác ngầm dành riêng cho mạng xã hội Facebook (nuôi nick Facebook, cày tương tác nhóm).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Đường dẫn Bài viết / Group:</strong> Link Facebook muốn nhắm mục tiêu.</li>\n<li><strong>Chuỗi thao tác:</strong><ul>\n<li>Xem Newsfeed ngẫu nhiên.</li>\n<li>Bình luận bài viết.</li>\n<li>Tự động nhắn tin qua Messenger.</li>\n</ul>\n</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Chạy Tự Động (Run Script):</strong> Kích hoạt hệ thống tương tác Facebook.</li>\n<li><strong>Gửi sang N8N (Webhook):</strong> Bắn tín hiệu sang luồng tự động hoá N8N để xử lý nâng cao.</li>\n</ul>\n"
    },
    {
        "title": "11. Cài đặt Hệ thống (Settings)",
        "html": "<h1>11. Cài đặt Hệ thống (Settings)</h1>\n<p><strong>Mục đích:</strong> Nơi cấu hình các thông số quan trọng nhất của hệ thống (API Keys, Tài khoản, Mật khẩu).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Cấu hình Email (SMTP):</strong> Nhập <code>SMTP Host</code>, <code>Port</code>, <code>Email</code>, và <code>App Password</code> để phần mềm gửi thư thông báo tự động.</li>\n<li><strong>Cấu hình API Key (AI):</strong> <ul>\n<li>API Key OpenAI (ChatGPT).</li>\n<li>API Key Google Gemini (Aistudio).</li>\n<li>API Key UModelverse.</li>\n</ul>\n</li>\n<li><strong>Model Văn bản &amp; Hình ảnh:</strong> Chọn mô hình AI mặc định (VD: <code>gpt-4o</code>, <code>dall-e-3</code>).</li>\n<li><strong>Mật khẩu &amp; Bảo mật:</strong> Khung đổi mật khẩu (<code>New password</code>, <code>Current password</code>).</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Lưu (Save):</strong> Lưu lại thông tin cài đặt.</li>\n<li><strong>Thêm Key (Add Key):</strong> Hỗ trợ thêm nhiều API Key để xoay vòng, chống sập giới hạn (Rate-limit).</li>\n<li><strong>Bật/Tắt Mì Tôm AI:</strong> Tính năng dùng AI nâng cao nội bộ.</li>\n</ul>\n"
    },
    {
        "title": "12. Bảng điều khiển (Dashboard)",
        "html": "<h1>12. Bảng điều khiển (Dashboard)</h1>\n<p><strong>Mục đích:</strong> Hiển thị tổng quan các số liệu và tiến độ hoạt động của phần mềm.</p>\n<h2>Ý nghĩa màn hình</h2>\n<ul>\n<li><strong>Thống kê:</strong> Liệt kê số lượng người dùng (Users), lượt xem trang (Pageviews), tỷ lệ tương tác (Engagement rate).</li>\n<li><strong>Tiến độ công việc (Jobs):</strong> Cho biết phần mềm đang chạy ẩn bao nhiêu tác vụ (như quét sitemap, render video, đăng bài tự động).</li>\n</ul>\n<h2>Các nút chức năng (Buttons)</h2>\n<ul>\n<li><strong>Xem báo cáo chi tiết:</strong> Mở rộng biểu đồ phân tích.</li>\n<li><strong>Làm mới (Refresh):</strong> Tải lại dữ liệu thống kê theo thời gian thực.</li>\n</ul>\n"
    },
    {
        "title": "13. Tổng quan Công cụ (Tools Overview)",
        "html": "<h1>13. Tổng quan Công cụ (Tools Overview)</h1>\n<p><strong>Mục đích:</strong> Cửa ngõ trung tâm (hub) điều hướng bạn đến các tính năng kỹ thuật và quản trị cốt lõi của phần mềm.</p>\n<h2>Danh sách các công cụ</h2>\n<ul>\n<li><strong>Công việc:</strong> Nơi quản lý, lên kịch bản, viết bài nhanh, tóm tắt nội dung.</li>\n<li><strong>Tên miền:</strong> Cấu hình và quản lý Domain.</li>\n<li><strong>Sitemap &amp; Từ điển:</strong> Hỗ trợ quá trình phân tích và viết bài bằng AI.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Kích hoạt / Truy cập:</strong> Mở giao diện làm việc chi tiết của module tương ứng.</li>\n</ul>\n"
    },
    {
        "title": "14. Danh sách Tiến trình ngầm (Jobs List)",
        "html": "<h1>14. Danh sách Tiến trình ngầm (Jobs List)</h1>\n<p><strong>Mục đích:</strong> Quản lý hàng chờ (Queue) của toàn bộ các tác vụ nặng trên hệ thống. Tránh treo phần mềm.</p>\n<h2>Ý nghĩa các thông số</h2>\n<ul>\n<li><strong>Tiến trình đang chạy (Processing):</strong> Các việc AI đang miệt mài làm (VD: &quot;Đang viết bài số 30/1000&quot;).</li>\n<li><strong>Tiến trình thất bại (Failed):</strong> Các việc bị lỗi (do hết mạng, API key hết tiền, v.v.).</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Hủy (Cancel):</strong> Buộc dừng một tiến trình đang chạy dở.</li>\n<li><strong>Chạy lại (Retry):</strong> Thử thực hiện lại một tiến trình vừa bị báo Lỗi (Failed).</li>\n<li><strong>Dọn dẹp (Clear):</strong> Xóa lịch sử tiến trình đã hoàn thành (Done).</li>\n</ul>\n"
    },
    {
        "title": "15. Quản lý Node WordPress (1 & 2)",
        "html": "<h1>15. Quản lý Node WordPress (1 &amp; 2)</h1>\n<p><strong>Mục đích:</strong> Liên kết ứng dụng AI.Type với các website WordPress bên ngoài để tự động xuất bản (Publish) bài viết.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>URL Website:</strong> Đường dẫn trang WordPress gốc.</li>\n<li><strong>Username &amp; App Password:</strong> Tên tài khoản và Mật khẩu ứng dụng (không phải mật khẩu gốc) để kết nối REST API một cách bảo mật.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Kiểm tra kết nối:</strong> Đảm bảo cấu hình đúng và website không bị Cloudflare hay Firewall chặn truy cập API.</li>\n<li><strong>Đồng bộ danh mục:</strong> Kéo cấu trúc Category của web về hệ thống AI.</li>\n<li><strong>Xóa / Sửa Node:</strong> Hủy hoặc thay đổi thông tin cấu hình website.</li>\n</ul>\n"
    },
    {
        "title": "16. Nhập dữ liệu WordPress (Importer)",
        "html": "<h1>16. Nhập dữ liệu WordPress (Importer)</h1>\n<p><strong>Mục đích:</strong> Di chuyển (Migrate) nội dung từ website WP cũ sang định dạng Markdown để hệ thống AI lưu trữ hoặc tiến hành viết lại (Spin).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Đọc file (Read file):</strong> Nơi bạn Upload file <code>.xml</code> xuất ra từ công cụ Export (Công cụ -&gt; Xuất) của mã nguồn WordPress.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Bắt đầu Nhập (Start Import):</strong> Đọc nội dung XML và chuyển vào kho lưu trữ (Archives) của AI.Type.</li>\n<li><strong>Lọc bài viết:</strong> Chọn các bài viết nhất định (theo danh mục hoặc tác giả) trước khi import.</li>\n</ul>\n"
    },
    {
        "title": "17. Cài đặt Tên miền (Domain Settings)",
        "html": "<h1>17. Cài đặt Tên miền (Domain Settings)</h1>\n<p><strong>Mục đích:</strong> Thêm mới và xác thực các tên miền nội bộ hoặc mạng lưới vệ tinh thuộc quyền sở hữu của bạn.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Tên miền (Domain URL):</strong> Nhập tên miền (VD: <code>ai.type.vn</code>).</li>\n<li><strong>Xác thực DNS / TXT:</strong> Chuỗi văn bản để xác thực quyền chủ sở hữu với máy chủ.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Cập nhật (Update):</strong> Lưu thông tin domain.</li>\n<li><strong>Kiểm tra trạng thái (Verify):</strong> Check xem bản ghi DNS đã trỏ đúng và cập nhật thành công chưa.</li>\n</ul>\n"
    },
    {
        "title": "18. Trình Tạo Ảnh AI (Image Generation)",
        "html": "<h1>18. Trình Tạo Ảnh AI (Image Generation)</h1>\n<p><strong>Mục đích:</strong> Tự động tạo ảnh minh hoạ cho bài viết dựa trên câu lệnh (Prompt).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Nội dung (Prompt):</strong> Miêu tả bức ảnh bạn muốn AI vẽ (Hỗ trợ tiếng Việt/Anh).</li>\n<li><strong>Kích thước (Aspect Ratio):</strong><ul>\n<li><code>16:9</code> (Dành cho YouTube / Ảnh bìa bài viết).</li>\n<li><code>9:16</code> (Dành cho TikTok / Reels / Shorts).</li>\n<li><code>1:1</code> (Dành cho Instagram / Vuông).</li>\n<li><code>4:5</code> (Facebook dọc).</li>\n<li><code>FB Link (1200x628)</code> (Ảnh preview chuẩn khi chia sẻ link web).</li>\n</ul>\n</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Tạo ảnh (Generate):</strong> Gọi AI thực thi tạo ảnh (Ví dụ: dùng module <code>dall-e-3</code>).</li>\n<li><strong>Phép màu (Magic / Auto_Awesome):</strong> AI tự động gợi ý / làm hay hơn câu lệnh Prompt của bạn.</li>\n<li><strong>Tải xuống (Download) &amp; Đính kèm (Paper-clip):</strong> Lưu về máy tính hoặc đính kèm ảnh ngay vào bài viết đang được soạn ở phân hệ khác.</li>\n</ul>\n"
    },
    {
        "title": "19. Tải Video MXH (Video Crawler / All-Tube)",
        "html": "<h1>19. Tải Video MXH (Video Crawler / All-Tube)</h1>\n<p><strong>Mục đích:</strong> Công cụ hàng loạt hỗ trợ tải (download) video không dính logo từ các MXH (TikTok, Youtube, Facebook, Reels).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Khung dán Link:</strong> Hỗ trợ dán nhiều URL video cùng lúc, mỗi dòng 1 link. Hỗ trợ hàng trăm link cùng lúc.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Quét Video (Scan):</strong> Đọc thông tin các link để lấy định dạng file, độ phân giải và tiêu đề gốc của video.</li>\n<li><strong>Tải Audio / Video:</strong><ul>\n<li>Tải định dạng hình ảnh và âm thanh gốc (.mp4).</li>\n<li>Tải riêng file âm thanh (.mp3) bằng cách bấm nút <code>Nghe audio</code>.</li>\n</ul>\n</li>\n</ul>\n"
    },
    {
        "title": "20. Bắt Trend Mạng Xã Hội (Facebook Trend)",
        "html": "<h1>20. Bắt Trend Mạng Xã Hội (Facebook Trend)</h1>\n<p><strong>Mục đích:</strong> Theo dõi và lọc ra các chủ đề, bài đăng đang Viral, đang Hot trên MXH để cướp ý tưởng viết bài nhanh chóng.</p>\n<h2>Thông tin hiển thị</h2>\n<ul>\n<li>Bảng xếp hạng các bài viết có lượng Like, Comment, Share tăng vọt (cao nhất).</li>\n<li>Hiển thị nguồn (Source) của trend (Tên fanpage, Nhóm bắt nguồn).</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Lấy bài viết này:</strong> Đẩy trực tiếp nội dung bài viral này sang mô-đun AI Writer để AI tự động xào lại (Spin) thành bài viết mới của bạn mà không dính bản quyền.</li>\n<li><strong>Refresh:</strong> Tải lại xu hướng (Trend) mới nhất theo mốc thời gian thực trong ngày.</li>\n</ul>\n"
    },
    {
        "title": "21. Khai phá Dữ liệu Lớn (Big Data / Data Crawler)",
        "html": "<h1>21. Khai phá Dữ liệu Lớn (Big Data / Data Crawler)</h1>\n<p><strong>Mục đích:</strong> Tự động Crawl dữ liệu quy mô lớn từ các sàn thương mại điện tử, danh bạ website hoặc Google Maps để lọc thông tin khách hàng, sản phẩm, và đối thủ cạnh tranh.</p>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Khởi chạy luồng (Run Flow):</strong> Kích hoạt hệ thống quét Big Data (Chạy ngầm).</li>\n<li><strong>Xuất CSV/Excel:</strong> Cho phép tải dữ liệu rác/thô đã được phân tích sau khi tiến trình crawl hoàn tất, dễ dàng nhập liệu vào CRM.</li>\n</ul>\n"
    },
    {
        "title": "22. Văn phong AI & Từ Đồng Nghĩa (Writing Styles & Synonym)",
        "html": "<h1>22. Văn phong AI &amp; Từ Đồng Nghĩa (Writing Styles &amp; Synonym)</h1>\n<p><strong>Mục đích:</strong> Giúp cá nhân hoá lối hành văn của AI, làm cho văn bản trở nên giống con người hơn và vượt qua được các công cụ kiểm tra AI (AI Content Detectors).</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Cấu hình thay thế từ:</strong> (Ví dụ: đổi <code>rất tốt</code> -&gt; <code>cực kỳ tuyệt vời</code>). Hệ thống sẽ tự động tìm các cụm từ này và hoán đổi sau khi AI đã viết xong bài.</li>\n<li><strong>Độ linh hoạt (Temperature):</strong> Kéo thanh trượt để chỉnh độ sáng tạo/ngẫu hứng của AI. Thông số càng cao, AI viết càng ngẫu nhiên và mới mẻ.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Áp dụng (Apply):</strong> Ghi nhớ cấu hình văn phong cho tất cả bài viết của chiến dịch hiện tại.</li>\n<li><strong>Xóa / Sửa:</strong> Quản lý và tùy chỉnh thư viện từ đồng nghĩa cá nhân của bạn.</li>\n</ul>\n"
    },
    {
        "title": "23. Đăng ký Dịch vụ (Subscription / Dollar)",
        "html": "<h1>23. Đăng ký Dịch vụ (Subscription / Dollar)</h1>\n<p><strong>Mục đích:</strong> Quản lý gói cước của tài khoản cá nhân, lịch sử thanh toán và gia hạn dịch vụ AI.Type.</p>\n<h2>Các trường nhập liệu (Inputs)</h2>\n<ul>\n<li><strong>Gói hiện tại:</strong> Thông tin License Key bạn đang dùng và ngày hết hạn hệ thống.</li>\n<li><strong>Chọn gói gia hạn:</strong> (Ví dụ: Gói Cơ bản / Chuyên cần / Cao cấp). Phụ thuộc vào nhu cầu sử dụng của bạn.</li>\n</ul>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Xác nhận gia hạn:</strong> Chuyển đến tiến trình thanh toán và tự động kích hoạt mã khóa (License Key).</li>\n<li><strong>Thêm mới / Cập nhật License Key:</strong> Trong trường hợp bạn mua Key thông qua đại lý, hãy điền mã bản quyền bạn vừa mua vào hệ thống bằng nút này.</li>\n</ul>\n"
    },
    {
        "title": "24. Quản lý Node Internet (Internet Nodes)",
        "html": "<h1>24. Quản lý Node Internet (Internet Nodes)</h1>\n<p><strong>Mục đích:</strong> Quản trị các điểm kết nối máy trạm (Node) do người dùng hoặc hệ thống triển khai để hỗ trợ cho mạng lưới Crawl dữ liệu và vượt tường lửa (Bypass Firewall/Captcha).</p>\n<h2>Các nút thao tác (Buttons)</h2>\n<ul>\n<li><strong>Xuất dữ liệu (Export):</strong> Kết xuất toàn bộ danh sách các Node Internet đang khả dụng dưới dạng file JSON hoặc CSV.</li>\n<li><strong>Bật / Tắt Node:</strong> Thay đổi trạng thái chia sẻ tài nguyên mạng của từng Node cụ thể. Bạn có thể tắt một node nếu nó đang bị quá tải hoặc lỗi mạng.</li>\n</ul>\n"
    }
];
